name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  build-app:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - uses: actions/download-artifact@v2
      with:
        path: dist
        name: dist
    - run: npm ci
    - run: npm run build:app

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - uses: actions/download-artifact@v2
      with:
        path: dist
        name: dist
    - run: npm ci
    - run: npm run test:ci
    - uses: actions/upload-artifact@v2
      with:
        name: ngx-multiple-dates
        path: coverage/ngx-multiple-dates/cobertura-coverage.xml
    - uses: actions/upload-artifact@v2
      with:
        name: ngx-multiple-dates
        path: coverage/ngx-multiple-dates-app/cobertura-coverage.xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/ngx-multiple-dates/cobertura-coverage.xml,./coverage/ngx-multiple-dates-app/cobertura-coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - run: npm ci
    - run: npm run lint
