name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run build:app
      - run: npm run test:ci
      - run: npm run lint
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist/ngx-multiple-dates-app
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - run: npm i is-ci
      - run: npm publish && npm dist-tag add ngx-multiple-dates@${{ steps.package-version.outputs.current-version }} stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
